# Use this docker-compose
# For creating a build environment for the project

version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
  redis:
    image: redis:5.0.5
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
