version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "30000:3306"
  redis:
    image: redis:5.0.5
    ports:
      - "30001:6379"
  adminer:
    image: adminer
    ports:
      - "40000:8080"
