# Use this docker-compose
# For creating a build environment for the project

version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    hostname: mysql
    env_file:
      - .env
    ports:
      - 3306:3306
  # phpmysql:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmysql
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:5.0.5
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
